name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env: 
      FULL_NAME: "Prilepo Polina Maksimovna"
      GROUP_NUMBER: "M3117"
      NICKNAME_GITHUB: "Uruli"
    steps:
      - name: Output information to console
        run: |
          echo "Full Name: ${{ env.FULL_NAME }}"
          echo "Group: ${{ env.GROUP_NUMBER }}"
          echo "GitHub Nick: ${{ github.actor }}"
      - name: Installing Python 3.13
        uses: actions/setup-python@v4        
        with:
          python-version: '3.13'
      #fourth step
      - name: Run tests
        run: |
          python -m unittest discover -s /home/runner/work/geometric_lib/geometric_lib/featTests
          
        #fifth step
      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 --ignore=F401 .
